export enum FileGenerationStates {
  LOADING = "Carregando",
  ASSET_NUMBER_CAPTURE = "Obtendo foto da placa de patrimônio",
  REVIEWING_MAIN_PHOTO = "Revisando foto principal da placa de patrimônio",
  REVIEWING_ASSET_NUMBER = "Revisando número de patrimônio",
  REVIEWING_ASSET_INFO = "Revisando informações do bem",
  ASSET_NUMBER_NOT_FOUND = "Não foi possível obter o número de patrimônio",
  ERROR_ASSET_NOT_FOUND = "Não foi possível encontrar um bem com esse número de patrimônio",
  ERROR_MORE_THAN_ONE_RESPONSIBLE = "Não foi possível adicionar esse bem: não é possível adicionar bens de responsáveis diferentes",
  ERROR_ASSET_INVALID_CONDITION = "Não foi possível adicionar esse bem: estado de conservação ou situação inválida",
  ERROR_ASSET_ALREADY_IN_FILE = "Não foi possível adicionar esse bem: esse bem já está presente no arquivo",
  ERROR_FILE_INCOMPLETE_ASSETS = "Este arquivo contém um bem incompleto. Não foi possível adicionar novo bem",
  ERROR_INTERNAL_ERROR = "Ocorreu um erro inesperado. Se o problema persistir, entre em contato com o suporte.",
  ERROR_FILE_INVALID_ASSETS = "Não foi possível gerar arquivo: esse arquivo contém bens incompletos",
  PHOTO_CAPTURE = "Obtendo foto do bem",
  REVIEWING_ASSET_PHOTO = "Revisando foto do bem",
  SELECTING_NEXT_ACTION = "Selecionando próxima ação",
}
